# Generated by Django 3.1.5 on 2021-01-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='collection',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='movies',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='movies',
            name='rate',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='movies',
            name='trailer',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='MovieItem',
        ),
    ]
