# Generated by Django 3.1.5 on 2021-01-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210129_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tvshows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('genres', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=1500)),
                ('trailer', models.CharField(default='', max_length=300)),
                ('rate', models.CharField(default='', max_length=300)),
                ('number_season', models.IntegerField(default=0, max_length=300)),
            ],
        ),
    ]
