# Generated by Django 3.1.5 on 2021-01-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tvshows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshows',
            name='number_season',
            field=models.IntegerField(default=0),
        ),
    ]
