# Generated by Django 3.1.5 on 2021-01-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210129_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='comingsoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('imgurl', models.CharField(max_length=300)),
            ],
        ),
    ]
