# Generated by Django 3.1.5 on 2021-01-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comingsoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
