# Generated by Django 3.1.5 on 2021-01-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210129_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(default='Movie', max_length=200),
        ),
    ]
