# Generated by Django 3.1.5 on 2021-01-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210131_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshows',
            name='suburl',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='vidurl',
        ),
        migrations.AlterField(
            model_name='episodes',
            name='imgurl',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='suburl',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movies',
            name='suburl',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
